import { describe, it, expect } from 'vitest';
import { Vector3 } from 'three';
import { SAFE_SPAWN_POOL } from '@/game/utils/safeSpawnPool';
import { SPAWN_POOL_GARDEN } from '@/game/rooms/garden';
import { GARDEN_AABBS } from '@/game/rooms/garden/roomAabbs';

// Mirrors filterPoolByAabbs padding so the test reflects the live filter.
const PADDING = 0.35;

function insideAabb(position: readonly [number, number, number]): boolean {
  const pt = new Vector3(position[0], position[1], position[2]);
  return GARDEN_AABBS.some((box) => box.clone().expandByScalar(PADDING).containsPoint(pt));
}

describe('garden spawn safety', () => {
  it('places every garden gnome on open ground — never inside a tree, bush, or prop', () => {
    // The garden pool is generated by filtering a grid against GARDEN_AABBS, so
    // a regression (e.g. a furniture AABB shrinking) would surface here.
    const buried = SPAWN_POOL_GARDEN.filter((sp) => insideAabb(sp.position)).map((sp) => sp.id);
    expect(buried).toEqual([]);
  });

  it('keeps the garden densely populated with hiding spots', () => {
    expect(SPAWN_POOL_GARDEN.length).toBeGreaterThanOrEqual(30);
  });

  it('keeps enough safe spawn points across the map for a full match', () => {
    expect(SAFE_SPAWN_POOL.length).toBeGreaterThanOrEqual(120);
  });
});
