import type { WeaponId, WeaponStats } from './types';

export const WEAPONS: Record<WeaponId, WeaponStats> = {
  'laser-pistol': {
    id: 'laser-pistol',
    displayName: 'Pistola Láser',
    description: 'Arma estándar. Rápida y equilibrada.',
    icon: '🔫',
    expRequired: 0,
    range: 30,
    fireRateMs: 250,
    beamColor: '#22d3ee',
    beamRadius: 0.025,
    recoilStrength: 1.0,
    hasScope: false,
    multiShot: 1,
    spreadAngleRad: 0,
  },
  'laser-rifle': {
    id: 'laser-rifle',
    displayName: 'Rifle Láser',
    description: 'Mayor alcance, beam grueso. Un poco más lenta.',
    icon: '🪖',
    expRequired: 200,
    range: 60,
    fireRateMs: 350,
    beamColor: '#22c55e',
    beamRadius: 0.04,
    recoilStrength: 1.3,
    hasScope: false,
    multiShot: 1,
    spreadAngleRad: 0,
  },
  'laser-sniper': {
    id: 'laser-sniper',
    displayName: 'Francotirador',
    description: 'Mira (RMB para zoom). Largo alcance, lento.',
    icon: '🎯',
    expRequired: 500,
    range: 150,
    fireRateMs: 800,
    beamColor: '#a855f7',
    beamRadius: 0.015,
    recoilStrength: 1.8,
    hasScope: true,
    multiShot: 1,
    spreadAngleRad: 0,
  },
  'plasma-spreader': {
    id: 'plasma-spreader',
    displayName: 'Plasma Spreader',
    description: '3 rayos en abanico. Devastador a corta distancia.',
    icon: '💥',
    expRequired: 1000,
    range: 15,
    fireRateMs: 600,
    beamColor: '#f59e0b',
    beamRadius: 0.03,
    recoilStrength: 2.0,
    hasScope: false,
    multiShot: 3,
    spreadAngleRad: 0.18,
  },
};

export const WEAPON_ORDER: readonly WeaponId[] = [
  'laser-pistol',
  'laser-rifle',
  'laser-sniper',
  'plasma-spreader',
];
